// Generated by CoffeeScript 1.9.1
var FQServer, FQServerPort, common, crypto, dgram, listenSocket, queue;

dgram = require('dgram');

common = require('./common');

crypto = require('crypto');

FQServer = common.parseConfig('server_addr');

FQServerPort = parseInt(common.parseConfig('server_port'));

queue = new common.queue();

listenSocket = dgram.createSocket('udp4');

listenSocket.bind(8053);

listenSocket.on('message', function(msg, rinfo) {
  console.log(rinfo);
  if (rinfo.address === FQServer && rinfo.port === FQServerPort) {
    rinfo = queue.find(common.getID(msg), function(r1, dft) {
      return r1.id === dft;
    });
    if ((rinfo != null)) {
      msg = common.decrypt(msg);
      return listenSocket.send(msg, 0, msg.length, rinfo.rinfo.port, rinfo.rinfo.address);
    } else {
      return console.log('Warning: DNS request response match failed');
    }
  } else {
    queue.enqueue({
      id: common.getID(msg),
      rinfo: rinfo
    });
    msg = common.encrypt(msg);
    return listenSocket.send(msg, 0, msg.length, FQServerPort, FQServer);
  }
});
