// Generated by CoffeeScript 1.9.1
var fs;

fs = require('fs');

exports.getID = function(msg) {
  return msg.readUIntBE(0, 2);
};

exports.parseConfig = (function(key) {
  var configJSON;
  configJSON = null;
  return (function() {
    if (configJSON == null) {
      this.configJSON = JSON.parse(fs.readFileSync('./config.json').toString());
    }
    return this.configJSON[key];
  })();
});
