// Generated by CoffeeScript 1.9.1
var config, crypto, dgram, dnsServer, idLen, init;

dgram = require('dgram');

config = require('./common');

crypto = require('crypto');

idLen = config.idLen;

dnsServer = "10.10.0.21";

init = function() {
  var s;
  s = dgram.createSocket('udp4');
  s.bind(12345);
  return s.on('message', function(msg, rinfo) {
    console.log(rinfo);
    if (rinfo.address !== dnsServer) {
      return s.send(msg, 0, msg.length, 53, dnsServer);
    } else {
      return s.send(msg, 0, msg.length, 8053, "127.0.0.1");
    }
  });
};

init();
